- hosts: all
  become: yes
  vars_files:
    - vars/main.yml
  roles:
    - { role: ansible-role-memcached }
    - ansible-role-certbot
    - custom-php-ini
    - { role: ansible-role-mysql }
    - { role: ansible-role-nginx }
    - { role: ansible-role-php }
